# Generated by Django 2.1.3 on 2018-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('BL', 'Blocked'), ('OP', 'Open'), ('IP', 'In Progress'), ('IR', 'In Review')], default='OP', max_length=2),
        ),
    ]
